// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_AnSx_b8P1ZYfqVCMxgX7P7Oi3QWeg3s',
    appId: '1:63423750679:web:6a7c7016b1fa8539187252',
    messagingSenderId: '63423750679',
    projectId: 'myflutterapp-483b7',
    authDomain: 'myflutterapp-483b7.firebaseapp.com',
    storageBucket: 'myflutterapp-483b7.firebasestorage.app',
    measurementId: 'G-72EXC17904',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXWRFd8GrtLlVEzjsbh0FwGxlzfOCt6ns',
    appId: '1:63423750679:android:4fe94f4b08699da0187252',
    messagingSenderId: '63423750679',
    projectId: 'myflutterapp-483b7',
    storageBucket: 'myflutterapp-483b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqVW4YkkC3EHBV21SU6NApu-Y2lbx2SA',
    appId: '1:63423750679:ios:a1e6c58f3754efce187252',
    messagingSenderId: '63423750679',
    projectId: 'myflutterapp-483b7',
    storageBucket: 'myflutterapp-483b7.firebasestorage.app',
    iosBundleId: 'com.example.newLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqVW4YkkC3EHBV21SU6NApu-Y2lbx2SA',
    appId: '1:63423750679:ios:a1e6c58f3754efce187252',
    messagingSenderId: '63423750679',
    projectId: 'myflutterapp-483b7',
    storageBucket: 'myflutterapp-483b7.firebasestorage.app',
    iosBundleId: 'com.example.newLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_AnSx_b8P1ZYfqVCMxgX7P7Oi3QWeg3s',
    appId: '1:63423750679:web:54e64dca08532b90187252',
    messagingSenderId: '63423750679',
    projectId: 'myflutterapp-483b7',
    authDomain: 'myflutterapp-483b7.firebaseapp.com',
    storageBucket: 'myflutterapp-483b7.firebasestorage.app',
    measurementId: 'G-BYE85JK839',
  );
}
